#!/bin/bash
# Blocks Edit/Write operations on protected files.
# Exit 0 = allow, Exit 2 = block (reason via stderr)

INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty')
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Normalize to relative path for pattern matching
REL_PATH="${FILE_PATH#"$CLAUDE_PROJECT_DIR"/}"

# --- Block: Claude Code settings files ---
if [[ "$REL_PATH" == ".claude/settings.json" ]] || [[ "$REL_PATH" == ".claude/settings.local.json" ]]; then
  echo "Protected: Claude Code settings should be modified deliberately via /hooks or the settings UI, not by Claude." >&2
  exit 2
fi

# --- Block: environment files ---
# .env.example is a committed template (no secrets) and is always allowed.
if [[ "$REL_PATH" != ".env.example" ]]; then
  if [[ "$REL_PATH" == .env* ]] || [[ "$REL_PATH" == *.env ]] || [[ "$REL_PATH" == *.env.* ]]; then
    echo "Protected: environment files (.env*) must not be edited by Claude. Modify manually." >&2
    exit 2
  fi
fi

# --- Block: lock files ---
if [[ "$REL_PATH" == "package-lock.json" ]]; then
  echo "Protected: package-lock.json is auto-generated. Run 'npm install' instead." >&2
  exit 2
fi

# --- Block: build output ---
if [[ "$REL_PATH" == dist/* ]]; then
  echo "Protected: dist/ is auto-generated. Run 'npm run build' instead." >&2
  exit 2
fi

# --- Block: node_modules ---
if [[ "$REL_PATH" == node_modules/* ]]; then
  echo "Protected: node_modules/ is managed by npm." >&2
  exit 2
fi

# --- Block: generated coverage/reports ---
if [[ "$REL_PATH" == coverage/* ]]; then
  echo "Protected: coverage/ is auto-generated by test runs." >&2
  exit 2
fi

# --- Block: editing existing migration files (allow creating new ones via Write) ---
if [[ "$REL_PATH" == src/migrations/*.cjs ]] && [[ "$TOOL_NAME" == "Edit" ]]; then
  echo "Protected: existing migration files are immutable once created. Create a new migration instead." >&2
  exit 2
fi

# --- Block: generated OpenAPI spec (regenerate via npm run docs:openapi:generate) ---
if [[ "$REL_PATH" == docs/openapi/lakira-backend-openapi.json ]]; then
  echo "Protected: OpenAPI spec is auto-generated. Run 'npm run docs:openapi:generate' instead." >&2
  exit 2
fi

# --- Block: CI/CD workflow files ---
if [[ "$REL_PATH" == .github/workflows/*.yml ]] || [[ "$REL_PATH" == .github/workflows/*.yaml ]]; then
  echo "Protected: CI/CD workflows should be modified deliberately. Confirm with the user before editing." >&2
  exit 2
fi

# --- Block: Docker Compose files ---
if [[ "$REL_PATH" == docker-compose*.yml ]] || [[ "$REL_PATH" == docker-compose*.yaml ]]; then
  echo "Protected: Docker Compose is infrastructure config. Confirm with the user before editing." >&2
  exit 2
fi

exit 0
