# docker-compose.test.yml

services:
  db:
    environment:
      POSTGRES_DB: lakira_test_db
      POSTGRES_USER: lakira_user
      POSTGRES_PASSWORD: lakira_password
    volumes:
      - db_test_data:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lakira_user -d lakira_test_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  app: # Node.js backend application service for tests
    build: # Define build context and Dockerfile
      context: .
      dockerfile: Dockerfile
    container_name: node_app_test
    env_file: # Load environment variables from .env.test
      - .env.test
    environment: # Set environment variables
      NODE_ENV: test # Run in test mode
    depends_on: # Ensure dependencies are running before starting the app
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks: # Connect to the backend network
      - backend

networks: # Define a dedicated Docker network for tests
  backend:
    name: backend_network # Use the same network as the main compose file

volumes:
  db_test_data:
    name: db_test_data_volume
  redis_data:
    name: redis_data_volume # Ensure redis data volume is also defined for test