import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import logger from "../src/utils/logger.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

type FeatureConfig = {
  type: "feature";
  title: string;
  rootDir: string;
  target: string;
  includeExtensions?: string[];
  excludeDirs?: string[];
};

type DocBundleConfig = {
  type: "doc_bundle";
  title: string;
  target: string;
  treeRoot: string;
  treeLabel?: string;
  files: {
    path: string;
    language: string;
  }[];
};

type TreeDocConfig = {
  type: "tree";
  title: string;
  target: string;
  rootDir: string;
  description: string;
  notes: string[];
  exclude?: string[];
};

type Config = FeatureConfig | DocBundleConfig | TreeDocConfig;

const featureConfigs: FeatureConfig[] = [
  {
    type: "feature",
    title: "Analytics Feature – Code Dump",
    rootDir: "src/features/analytics",
    target:
      "documents/documentation/code-for-export-reference/be-analytics-feature-codes.md",
  },
  {
    type: "feature",
    title: "Auth Feature – Code Dump",
    rootDir: "src/features/auth",
    target:
      "documents/documentation/code-for-export-reference/be-auth-feature-codes.md",
  },
  {
    type: "feature",
    title: "Metric Feature – Code Dump",
    rootDir: "src/features/metric",
    target:
      "documents/documentation/code-for-export-reference/be-metric-feature-codes.md",
  },
  {
    type: "feature",
    title: "Metric Category Feature – Code Dump",
    rootDir: "src/features/metric-category",
    target:
      "documents/documentation/code-for-export-reference/be-metric-category-feature-codes.md",
  },
  {
    type: "feature",
    title: "Metric Log Feature – Code Dump",
    rootDir: "src/features/metric-log",
    target:
      "documents/documentation/code-for-export-reference/be-metric-log-feature-codes.md",
  },
  {
    type: "feature",
    title: "Metric Settings Feature – Code Dump",
    rootDir: "src/features/metric-settings",
    target:
      "documents/documentation/code-for-export-reference/be-metric-settings-feature-codes.md",
  },
];

const docBundleConfigs: DocBundleConfig[] = [
  {
    type: "doc_bundle",
    title: "documents/ci-cd Contents",
    treeRoot: "documents/ci-cd",
    treeLabel: "ci-cd",
    target:
      "documents/documentation/code-for-export-reference/be-documents-ci-cd-content.md",
    files: [
      { path: "documents/ci-cd/CI_CD_STRATEGY.md", language: "markdown" },
      {
        path: "documents/ci-cd/backend/ENVIRONMENTS_MATRIX.md",
        language: "markdown",
      },
      {
        path: "documents/ci-cd/backend/GITHUB_ACTIONS_PIPELINE_CHECKLIST.md",
        language: "markdown",
      },
      {
        path: "documents/ci-cd/backend/GITHUB_ACTIONS_PIPELINE_PLAN.md",
        language: "markdown",
      },
      {
        path: "documents/ci-cd/backend/GITHUB_ACTIONS_WORKFLOW_GUIDELINES.md",
        language: "markdown",
      },
      {
        path: "documents/ci-cd/backend/JENKINS_NOTES.md",
        language: "markdown",
      },
      {
        path: "documents/ci-cd/backend/README.md",
        language: "markdown",
      },
      {
        path: "documents/ci-cd/frontend/ENVIRONMENTS_MATRIX.md",
        language: "markdown",
      },
      {
        path: "documents/ci-cd/frontend/GITHUB_ACTIONS_PIPELINE_CHECKLIST.md",
        language: "markdown",
      },
      {
        path: "documents/ci-cd/frontend/GITHUB_ACTIONS_PIPELINE_PLAN.md",
        language: "markdown",
      },
      {
        path: "documents/ci-cd/frontend/README.md",
        language: "markdown",
      },
      {
        path: ".github/workflows/backend-ci.yml",
        language: "yaml",
      },
    ],
  },
];

const treeDocConfigs: TreeDocConfig[] = [
  {
    type: "tree",
    title: "Lakira Backend Project Structure (2025-12-11)",
    target:
      "documents/documentation/code-for-export-reference/be-project-structure-20251211.md",
    rootDir: ".",
    description:
      "This catalog lists every file currently living in the repository workspace, including all material inside the `documents/` tree. Generated by walking the working tree and excluding only automated or framework-only internals (`node_modules`, `.git`, `.next`, `.turbo`, `.idea`, `.vscode`, `dist`, `coverage`, `logs`). That keeps the focus on user-authored assets.",
    notes: [
      "Includes every file currently present in the working tree (tracked or not) so long as it is user-managed.",
      "Automatically omitted generated or dependency-heavy internals (`node_modules`, `.next`, `dist`, `coverage`, `logs`, tooling config folders) per the request.",
      "`.env*` files are listed for completeness, but rotate secrets if this doc is ever shared externally.",
    ],
    exclude: [
      ".git",
      "node_modules",
      ".next",
      ".turbo",
      ".idea",
      ".vscode",
      "dist",
      "coverage",
      "logs",
    ],
  },
];

const configs: Config[] = [
  ...featureConfigs,
  ...docBundleConfigs,
  ...treeDocConfigs,
];

async function main() {
  for (const config of configs) {
    switch (config.type) {
      case "feature":
        generateFeatureDoc(config);
        break;
      case "doc_bundle":
        generateDocBundle(config);
        break;
      case "tree":
        generateTreeDoc(config);
        break;
    }
  }
}

function generateFeatureDoc(config: FeatureConfig) {
  const rootPath = path.resolve(repoRoot, config.rootDir);
  const tree = buildIndentedTree(rootPath, {
    startLabel: "./",
    exclude: new Set(config.excludeDirs ?? []),
  });
  const files = listFiles(rootPath, {
    includeExtensions: config.includeExtensions ?? [".ts", ".tsx"],
    excludeDirs: new Set(config.excludeDirs ?? []),
  });

  let doc = `# ${config.title}\n\n`;
  doc += "## Directory Schema\n";
  doc += "```\n";
  doc += `${tree}\n`;
  doc += "```\n\n";
  doc += "## Source Files\n\n";

  for (const file of files) {
    const relPath = toPosixPath(path.relative(repoRoot, file));
    const contents = fs.readFileSync(file, "utf-8");
    doc += `//file:${relPath}\n${contents}\n\n`;
  }

  writeFile(config.target, doc.trimEnd() + "\n");
}

function generateDocBundle(config: DocBundleConfig) {
  const rootPath = path.resolve(repoRoot, config.treeRoot);
  const tree = buildBranchTree(rootPath, {
    label: config.treeLabel ?? path.basename(rootPath),
  });

  let doc = `# ${config.title}\n\n`;
  doc += "## Directory Tree\n\n";
  doc += "```\n";
  doc += `${tree}\n`;
  doc += "```\n\n";

  for (const fileConfig of config.files) {
    const filePath = path.resolve(repoRoot, fileConfig.path);
    const contents = fs.readFileSync(filePath, "utf-8");
    doc += `## File: ${toPosixPath(fileConfig.path)}\n\n`;
    doc += "```" + fileConfig.language + "\n";
    doc += `${contents}\n`;
    doc += "```\n\n";
  }

  writeFile(config.target, doc.trimEnd() + "\n");
}

function generateTreeDoc(config: TreeDocConfig) {
  const rootPath = path.resolve(repoRoot, config.rootDir);
  const tree = buildBranchTree(rootPath, {
    label: ".",
    exclude: new Set(config.exclude ?? []),
  });

  let doc = `# ${config.title}\n\n`;
  doc += `${config.description}\n\n`;
  doc += "## Directory Tree\n\n";
  doc += "```text\n";
  doc += `${tree}\n`;
  doc += "```\n\n";
  doc += "## Notes\n";
  for (const note of config.notes) {
    doc += `- ${note}\n`;
  }

  writeFile(config.target, doc.trimEnd() + "\n");
}

function listFiles(
  rootPath: string,
  options: { includeExtensions: string[]; excludeDirs: Set<string> },
) {
  const files: string[] = [];
  const { includeExtensions, excludeDirs } = options;
  const visit = (current: string) => {
    const entries = fs
      .readdirSync(current, { withFileTypes: true })
      .filter((entry) => !shouldSkip(entry.name, excludeDirs))
      .sort(sortEntries);

    for (const entry of entries) {
      const entryPath = path.join(current, entry.name);
      if (entry.isDirectory()) {
        visit(entryPath);
      } else {
        const ext = path.extname(entry.name);
        if (includeExtensions.includes(ext)) {
          files.push(entryPath);
        }
      }
    }
  };

  visit(rootPath);
  return files;
}

function buildIndentedTree(
  rootPath: string,
  options: { startLabel: string; exclude?: Set<string> },
) {
  const lines: string[] = [options.startLabel];
  const indentUnit = "    ";
  const exclude = options.exclude ?? new Set<string>();

  const walk = (current: string, indent: string) => {
    const entries = fs
      .readdirSync(current, { withFileTypes: true })
      .filter((entry) => !shouldSkip(entry.name, exclude))
      .sort(sortEntries);

    for (const entry of entries) {
      const suffix = entry.isDirectory() ? "/" : "";
      lines.push(`${indent}${entry.name}${suffix}`);
      if (entry.isDirectory()) {
        walk(path.join(current, entry.name), indent + indentUnit);
      }
    }
  };

  walk(rootPath, indentUnit);
  return lines.join("\n");
}

function buildBranchTree(
  rootPath: string,
  options: { label: string; exclude?: Set<string> },
) {
  const lines: string[] = [options.label];
  const exclude = options.exclude ?? new Set<string>();

  const walk = (current: string, prefix: string) => {
    const entries = fs
      .readdirSync(current, { withFileTypes: true })
      .filter((entry) => !shouldSkip(entry.name, exclude))
      .sort(sortEntries);

    entries.forEach((entry, index) => {
      const isLast = index === entries.length - 1;
      const branch = isLast ? "└── " : "├── ";
      const suffix = entry.isDirectory() ? "/" : "";
      lines.push(`${prefix}${branch}${entry.name}${suffix}`);
      if (entry.isDirectory()) {
        const nextPrefix = prefix + (isLast ? "    " : "│   ");
        walk(path.join(current, entry.name), nextPrefix);
      }
    });
  };

  walk(rootPath, "");
  return lines.join("\n");
}

function shouldSkip(name: string, exclude: Set<string>) {
  if (name === ".DS_Store") return true;
  return exclude.has(name);
}

function sortEntries(a: fs.Dirent, b: fs.Dirent) {
  if (a.isDirectory() && !b.isDirectory()) return -1;
  if (!a.isDirectory() && b.isDirectory()) return 1;
  return a.name.localeCompare(b.name);
}

function writeFile(targetRelative: string, contents: string) {
  const targetPath = path.resolve(repoRoot, targetRelative);
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, contents, "utf-8");
  logger.info(`Updated ${toPosixPath(path.relative(repoRoot, targetPath))}`);
}

function toPosixPath(inputPath: string) {
  return inputPath.split(path.sep).join("/");
}

main().catch((err) => {
  logger.error("[EXPORT REFERENCE] Generation failed", err);
  process.exitCode = 1;
});
